import Pkg; Pkg.add("ArgParse")
import Pkg; Pkg.add("DelimitedFiles")
import Pkg; Pkg.add("Dates")
import Pkg; Pkg.add("Plots")
import Pkg; Pkg.add("LaTeXStrings")
import Pkg; Pkg.add("SpecialFunctions")